name: ClaudeCoder

on:
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  process-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - run: ls -R /home/runner/work/remotemusic/
    # - name: ClaudeCoderAction
    #   uses: EndemicMedia/claudecoder@main
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
